# Generated by Django 4.1.4 on 2022-12-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('datestr', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('ticketID', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('ticket_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketswatcher.concert')),
            ],
        ),
    ]
