# Generated by Django 4.1.4 on 2022-12-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0003_alter_concert_image_alter_concert_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='ticket_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
