# Generated by Django 4.1.4 on 2022-12-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0004_alter_concert_ticket_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
