# Generated by Django 4.1.4 on 2022-12-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0005_rename_tickets_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('concerts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketswatcher.concert')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='identifier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WatcherTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.IntegerField()),
                ('reduction_handicapped', models.BooleanField()),
                ('reduction_student', models.BooleanField()),
                ('reduction_child', models.BooleanField()),
                ('reduction_under30', models.BooleanField()),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketswatcher.watcher')),
            ],
        ),
    ]
