# Generated by Django 4.1.4 on 2022-12-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0007_ticketreductiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reduction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketswatcher.ticketreductiontype'),
        ),
    ]
