# Generated by Django 4.1.4 on 2022-12-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0008_ticket_reduction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchertickets',
            name='reduction_child',
        ),
        migrations.RemoveField(
            model_name='watchertickets',
            name='reduction_handicapped',
        ),
        migrations.RemoveField(
            model_name='watchertickets',
            name='reduction_student',
        ),
        migrations.RemoveField(
            model_name='watchertickets',
            name='reduction_under30',
        ),
        migrations.AddField(
            model_name='watchertickets',
            name='types',
            field=models.ManyToManyField(to='ticketswatcher.ticketreductiontype'),
        ),
    ]
