# Generated by Django 4.1.4 on 2022-12-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0010_watcher_max_price_watcher_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reduction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketswatcher.ticketreductiontype'),
        ),
    ]
