# Generated by Django 4.1.4 on 2022-12-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0011_alter_ticket_reduction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
