# Generated by Django 4.1.4 on 2022-12-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0012_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sort',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
