# Generated by Django 4.1.4 on 2022-12-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0013_ticket_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='venue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
