# Generated by Django 4.1.4 on 2022-12-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0014_concert_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watcher',
            old_name='concerts',
            new_name='concert',
        ),
    ]
