# Generated by Django 4.1.4 on 2022-12-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0015_rename_concerts_watcher_concert'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='num_tickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
