# Generated by Django 4.1.4 on 2022-12-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0016_watcher_num_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='uuid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
