# Generated by Django 4.1.4 on 2023-10-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0017_watcher_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='details',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
