# Generated by Django 4.1.4 on 2023-11-04 17:26python manage.py squashmigrations <appname> <squashfrom> <squashto>

python manage.py help squashmigrations
https://docs.djangoproject.com/en/dev/topics/migrations/#migration-squashing

This will give you more granular control over which migrations to squash, and let you keep a cleaner commit history. Deleting + recreating all migrations may cause other issues such as circular dependencies depending on how models are constructed.



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0021_alter_watcher_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='types',
            field=models.ManyToManyField(blank=True, to='ticketswatcher.ticketreductiontype'),
        ),
    ]
