# Generated by Django 3.2.23 on 2024-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0022_alter_watcher_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='last_ticket_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
