# Generated by Django 3.2.23 on 2024-10-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswatcher', '0023_auto_20240204_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='last_found',
            field=models.BooleanField(null=True),
        ),
    ]
